services:
  mysql:
    image: 'mysql:latest'
    env_file: ./.env
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_PORT
